snapshot: lts-24.35

packages:
- .

extra-deps:
  - rel8-1.7.0.0
  - github: isovector/servant-ede
    commit: bbbd3bf21c62fd828368506c865776d5ad0af018

nix:
  packages:
    - postgresql
    - pkg-config
    - openssl
    - libz
    - cacert
